QTDIR ?= /opt/Qtopia/qt-2.3.2
QPESDK ?= /opt/murphytalk-sdk/qtopia-free-1.7.0
CXX ?= arm-cacko-linux-gnu-g++
CC ?= arm-cacko-linux-gnu-gcc
MOC ?= $(QTDIR)/src/moc/moc

CXXFLAGS = -pipe -DQT_QWS_SL5XXX -DQT_QWS_CUSTOM -DQWS -DQT_NO_PROPERTIES -DQT_NO_DRAGANDDROP -fno-exceptions -fno-rtti -Wall -W -O2 -DNO_DEBUG
INCPATH = -Isrc -Ivendor/md4c -I$(QPESDK)/include -I$(QTDIR)/include
LFLAGS =
LIBS = -Lcompat-lib -L$(QTDIR)/lib -lqpe -lqte -ljpeg

SOURCES = \
	src/main.cpp \
	src/MainWindow.cpp \
	src/MarkdownActions.cpp \
	src/MdEdit.cpp \
	src/MdView.cpp \
	src/TextPrompt.cpp \
	src/MdParser.cpp \
	src/TodoTxt.cpp \
	src/TodoMd.cpp \
	src/FileUtil.cpp \
	moc_MainWindow.cpp \
	moc_MdEdit.cpp \
	moc_MdView.cpp

OBJECTS = $(SOURCES:.cpp=.o) src/MdRichText.o vendor/md4c/md4c.o vendor/md4c/entity.o
TARGET = DIST/zaurusmd

all: $(TARGET)

$(TARGET): $(OBJECTS)
	rm -rf DIST
	mkdir -p DIST
	$(CXX) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS)

moc_MainWindow.cpp: src/MainWindow.h
	$(MOC) src/MainWindow.h -o moc_MainWindow.cpp

moc_MdEdit.cpp: src/MdEdit.h
	$(MOC) src/MdEdit.h -o moc_MdEdit.cpp

moc_MdView.cpp: src/MdView.h
	$(MOC) src/MdView.h -o moc_MdView.cpp

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c -O2 -Wall $(INCPATH) -o $@ $<

clean:
	rm -f src/*.o vendor/md4c/*.o *.o moc_MainWindow.cpp moc_MdEdit.cpp moc_MdView.cpp
	rm -rf DIST IPK *.ipk control.tar.gz data.tar.gz debian-binary
