#!/bin/sh
set -eu
ARMSDK=/opt/cross/arm/2.95.3-2.15
mkdir -p test-runtime
"$ARMSDK/bin/arm-cacko-linux-gnu-gcc" -O2 -static -Isrc -Ivendor/md4c \
    tests/render-cli.c src/MdRichText.c vendor/md4c/md4c.c vendor/md4c/entity.c \
    -o test-runtime/render-arm
count=0
for input in test-runtime/corpus-cases/case-*.in; do
    stem=${input%.in}
    task=$(cat "$stem.task")
    status=0
    # The optional argument is generated by test-corpus.py and is numeric only.
    qemu-arm test-runtime/render-arm $task < "$input" \
        > test-runtime/arm.out 2> test-runtime/arm.err || status=$?
    if [ "$status" != "$(cat "$stem.status")" ]; then
        echo "FAIL $stem: status $status"
        cat test-runtime/arm.err
        exit 1
    fi
    qemu-arm test-runtime/render-arm --compare "$stem.out" test-runtime/arm.out
    count=$((count + 1))
done
echo "PASS $count ARM outputs match native corpus results"
